# Site settings
title: Network Blender
header-img: img/home-bg.png
email: william.barela.dev@gmail.com
copyright_name: WilliamBarela
description: > # this means to ignore newlines until "baseurl:"
  Weaving structural holes in the journey of web development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: FullStackDev0
github_username:  WilliamBarela
learn_profile: WilliamBarela
email_username: william.barela.dev@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

theme: jekyll-theme-cayman